In [1]:
import numpy as np

In [14]:
# рассчет обратной матрицы "на бумаге"
# 1 2 3
# 4 0 6
# 7 8 9

# M
m = np.array([[0-6*8, 4*9-6*7, 4*8], [2*9-3*8, 1*9-3*7, 1*8-2*7], [2*6, 1*6-3*4, 0-2*4]], float)
print('M=', m)

# A*
for i in range(3):
    for j in range(3):
        m[i, j] *= 1 if (i + j) % 2 == 0 else -1
        
print('A*=', m)

# A*(T)
m = m.transpose()
print('A*(T)=', m)

# det
det = 60.0 # уже рассчитан для этой матрицы в зададнии 2

# A(-1) = A*(T)/det
for i in range(3):
    for j in range(3):
        m[i, j] /= det
        
print('A(-1)=', m)

M= [[-48.  -6.  32.]
 [ -6. -12.  -6.]
 [ 12.  -6.  -8.]]
A*= [[-48.   6.  32.]
 [  6. -12.   6.]
 [ 12.   6.  -8.]]
A*(T)= [[-48.   6.  12.]
 [  6. -12.   6.]
 [ 32.   6.  -8.]]
A(-1)= [[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [15]:
# проверка через расчет численным методом
a = np.array([[1,2,3], [4,0,6], [7,8,9]])
p = np.linalg.inv(a)
print(p)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
